# Generated by Django 4.1.4 on 2023-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="info",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
